version: "3.8"

services:
  node:
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
        - "8000:3000"
    container_name: node
    command: 
        pm2-runtime start bin/www --watch --name main
    environment:
      - NODE_ENV=production
    networks: 
      - backend
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
    container_name: "mongodb"
    ports:
      - "27017:27017"
    networks: 
      - backend
  redis:
    image: "redis"
    container_name: redis
    ports:
      - "6379:6379"
    volumes: 
      - ./data/redis
    restart: always
    networks: 
      - backend
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks: 
      - backend

networks:
  backend:
    driver: bridge
